### PR TITLE
License via Apache2

### PR DESCRIPTION
**Pull request by ellieayla**
Propose to license via Apache2

### CODE REVIEW

**Comment by ellieayla** [comment]
@Myrmidor @gabe-camp @danieldsj please reply here with your approval

**Comment by gabe-camp** [comment]
Ship it

**Review by danieldsj — APPROVED** [review]
I approve.

**Review by gabe-camp — APPROVED** [review]
ship it

**Review by Myrmidor — APPROVED** [review]

**Comment by ellieayla** [comment]
All contributors approved; merging.

**Comment by mickfuzz** [comment]
Many thanks!
I'll integrate this now!

**Pull request merged**
